import type { ClientPortalData } from "./ClientPortalView";

const today = new Date().toISOString().slice(0, 10);

export function getDemoClientPortalData(code: string): ClientPortalData | null {
  const normalized = decodeURIComponent(code).trim().toLowerCase();

  if (!normalized || normalized === "demo" || normalized === "estela" || normalized === "estela-5tel") {
    return {
      client: {
        id: "demo-client-estela",
        name: "Estela",
        phone: "+54 9 236 555-0101",
        notes: "Vista cliente demo. Link privado revocable.",
      },
      operations: [
        {
          id: "demo-op-estela-telefonos",
          public_code: "ESTELA-5TEL",
          operation_date: today,
          provider_name: "Génesis / compra 5 teléfonos",
          package_count: 5,
          logistics_status: "despachado",
          financial_status: "pendiente",
          note: "Operación con cinco destinos. Cada número de guía funciona como seguimiento del pedido enviado.",
          pass_amount: 550,
          total_amount: 882000,
          paid_amount_ars: 0,
          paid_amount_usd: 200,
          balance_amount: 525000,
          shipments: [
            {
              company: "Vía Cargo",
              guide_number: "VC-10253",
              guide_amount: 57000,
              guide_paid_by: "cliente",
              guide_payment_status: "pagada_por_cliente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Matías",
              recipient_identity_number: "33.547.272",
              destination_detail: "Retira Matías por indicación de Estela. La guía se paga en destino.",
              pass_usd_amount: 80,
              pass_paid_usd_amount: 50,
              pass_date: today,
              pass_note: "Pase asociado a esta guía.",
              guide_cost_amount: 57000,
              guide_surcharge_percent: 2,
              guide_charge_amount: 58140,
              dispatch_date: today,
            },
            {
              company: "Buspack",
              guide_number: "BP-10254",
              guide_amount: 38000,
              guide_paid_by: "cliente",
              guide_payment_status: "pagada_por_cliente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Juan",
              recipient_identity_number: "31.111.111",
              destination_detail: "Entrega a cliente de Estela.",
              pass_usd_amount: 150,
              pass_paid_usd_amount: 80,
              pass_date: today,
              pass_note: "Pase asociado a esta guía.",
              guide_cost_amount: 38000,
              guide_surcharge_percent: 0,
              guide_charge_amount: 38000,
              dispatch_date: today,
            },
            {
              company: "Crucero Express",
              guide_number: "CE-10255",
              guide_amount: 42000,
              guide_paid_by: "cliente",
              guide_payment_status: "pagada_por_cliente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Laura",
              recipient_identity_number: "29.222.222",
              destination_detail: "Entrega a tercero autorizado.",
              pass_usd_amount: 200,
              pass_paid_usd_amount: 0,
              pass_date: today,
              pass_note: "Pase asociado a esta guía.",
              guide_cost_amount: 42000,
              guide_surcharge_percent: 0,
              guide_charge_amount: 42000,
              dispatch_date: today,
            },
            {
              company: "Correo Argentino",
              guide_number: "CA-10256",
              guide_amount: 26000,
              guide_paid_by: "cliente",
              guide_payment_status: "pagada_por_cliente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Pedro",
              recipient_identity_number: "30.333.333",
              destination_detail: "Entrega a cuarto destinatario.",
              pass_usd_amount: 70,
              pass_paid_usd_amount: 70,
              pass_date: today,
              pass_note: "Pase asociado a esta guía.",
              guide_cost_amount: 26000,
              guide_surcharge_percent: 0,
              guide_charge_amount: 26000,
              dispatch_date: today,
            },
            {
              company: "Buspack",
              guide_number: "BP-10257",
              guide_amount: 57000,
              guide_paid_by: "pendiente",
              guide_payment_status: "pendiente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Carla",
              recipient_identity_number: "32.444.444",
              destination_detail: "Guía no pagada / pendiente.",
              pass_usd_amount: 50,
              pass_paid_usd_amount: 0,
              pass_date: today,
              pass_note: "Pase asociado a esta guía.",
              guide_cost_amount: 57000,
              guide_surcharge_percent: 0,
              guide_charge_amount: 57000,
              dispatch_date: today,
            },
          ],
          payments: [
            { concept: "Pago parcial de pases", method: "efectivo_dolares", currency: "USD", amount: 200, paid_at: new Date().toISOString(), note: "Aplicado a VC-10253, BP-10254 y CA-10256" },
          ],
        },
      ],
    };
  }

  if (normalized === "matias" || normalized === "matias-pases") {
    return {
      client: {
        id: "demo-client-matias",
        name: "Matías",
        phone: "+54 9 236 555-0202",
        notes: "Pases pendientes ligados a guías.",
      },
      operations: [
        {
          id: "demo-op-matias-pases",
          public_code: "MATIAS-PASES",
          operation_date: today,
          provider_name: "Compras varias / pases pendientes",
          package_count: 3,
          logistics_status: "deposito_a",
          financial_status: "pendiente",
          note: "Los pases quedan en USD. El equivalente en pesos se calcula con el dólar del día.",
          pass_amount: 430,
          total_amount: 702000,
          paid_amount_ars: 0,
          paid_amount_usd: 0,
          balance_amount: 702000,
          shipments: [
            {
              company: "Vía Cargo",
              guide_number: "VC-20080",
              guide_amount: 50000,
              guide_paid_by: "cliente",
              guide_payment_status: "pagada_por_cliente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Matías",
              recipient_identity_number: "33.547.272",
              destination_detail: "Guía paga en destino.",
              pass_usd_amount: 80,
              pass_paid_usd_amount: 50,
              pass_date: today,
              pass_note: "Pase variable cargado manualmente.",
              guide_cost_amount: 50000,
              guide_surcharge_percent: 2,
              guide_charge_amount: 51000,
              dispatch_date: null,
            },
            {
              company: "Correo Argentino",
              guide_number: "CA-20150",
              guide_amount: 30000,
              guide_paid_by: "cliente",
              guide_payment_status: "pagada_por_cliente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Matías",
              recipient_identity_number: "33.547.272",
              destination_detail: "Pase asociado.",
              pass_usd_amount: 150,
              pass_paid_usd_amount: 80,
              pass_date: today,
              pass_note: "Pase variable cargado manualmente.",
              guide_cost_amount: 30000,
              guide_surcharge_percent: 0,
              guide_charge_amount: 30000,
              dispatch_date: null,
            },
            {
              company: "Buspack",
              guide_number: "BP-20200",
              guide_amount: 57000,
              guide_paid_by: "pendiente",
              guide_payment_status: "pendiente",
              guide_payment_method: null,
              guide_payment_currency: null,
              guide_paid_amount: 0,
              recipient_name: "Matías",
              recipient_identity_number: "33.547.272",
              destination_detail: "Pase asociado.",
              pass_usd_amount: 200,
              pass_paid_usd_amount: 0,
              pass_date: today,
              pass_note: "Pase variable cargado manualmente.",
              guide_cost_amount: 57000,
              guide_surcharge_percent: 0,
              guide_charge_amount: 57000,
              dispatch_date: null,
            },
          ],
          payments: [],
        },
      ],
    };
  }

  return null;
}
